# the k8s API version
apiVersion: batch/v1
# the type of an object
kind: CronJob
metadata:
  name: batch-job-every-fifteen-minutes
spec:
  # the cron job time format
  # 0 15 30 45 | hours are missed | days are missed | months are missed | days of a week is missed |
  schedule: "0, 15, 30, 45 * * * *"

  # Job object template
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job
