# k8s API version
apiVersion: v1

# object's type
kind: Pod

# metadata of object
metadata:
  creationTimestamp: "2024-09-05T11:13:31Z"
  generateName: kubia-74cf69898-
  labels:
    app: kubia
    pod-template-hash: 74cf69898
  name: kubia-74cf69898-m9sfg
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kubia-74cf69898
    uid: 7716d6ca-ea09-4c87-8112-3a882e9a9948
  resourceVersion: "10459"
  uid: f6a44e55-e94d-4014-9024-465ba29859b3

# specification of object
spec:
  containers:
  - image: hex0xdead/kubia
    imagePullPolicy: Always
    name: kubia
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-96ktp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-96ktp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

# statuses of object  
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-09-05T11:35:43Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-09-05T11:13:31Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-09-05T11:35:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-09-05T11:35:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-09-05T11:13:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f23db6427533f5a5a942732f053c66312d3685c459a17a1ebfdf5b8f2c21c491
    image: hex0xdead/kubia:latest
    imageID: docker-pullable://hex0xdead/kubia@sha256:abc98194d8bc443bb57ef2076e21336b00fef3bf22979996e4185cced8046747
    lastState:
      terminated:
        containerID: docker://2aa554778c20c85521c9a0bc6b308aebd1534baab423bf8ab3301e31dfa6a270
        exitCode: 137
        finishedAt: "2024-09-05T11:35:25Z"
        reason: Error
        startedAt: "2024-09-05T11:13:35Z"
    name: kubia
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-09-05T11:35:42Z"
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  phase: Running
  podIP: 10.244.0.14
  podIPs:
  - ip: 10.244.0.14
  qosClass: BestEffort
  startTime: "2024-09-05T11:13:31Z"