apiVersion: v1
kind: Endpoints # The endpoints of the specific service
metadata:
  name: external-service # the name of the endpoints object should match the service's name
# "subsets" represents the IPs the service refers to
subsets:
  - addresses:
      - ip: 11.11.11.11
      - ip: 22.22.22.22
    # The target port of the endpoints
    ports:
      - port: 80
